# Generated by Django 3.1.3 on 2023-01-17 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0005_auto_20200830_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='clicked',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='route',
            name='device',
            field=models.CharField(default='Unkown', max_length=100),
        ),
        migrations.AddField(
            model_name='route',
            name='req_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='res_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='user',
            field=models.CharField(default='admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='key',
            field=models.TextField(default='7sH1EAz', help_text='Use generated short link or add any random characters of your choice to shorten it.', unique=True),
        ),
    ]
