# Generated by Django 3.1.3 on 2023-01-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('router', '0008_auto_20230118_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='key',
            field=models.TextField(default='jNTBg3f', help_text='Use generated short link or add any random characters of your choice to shorten it.', unique=True),
        ),
    ]
